### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by Myndex** [cyrezdev/a11y-apca-sass#1]
Hi Cyril @cyrezdev 

First, **WOW. What a project this is**, It is impressive, one of the best iterations of an APCA based library I've seen, possibly the best——I have not exercised it as yet, but have gone through the code, and all the basics look very good. I am not familiar with sass, so I might be missing unique features you might have going on.

There are a few minor bits that need to be addressed before a public release IMO, and I appreciate you asking for review.

**ALSO, just as an FYI, before this repo goes public, I may want to delete this issue thread, as it may contain privileged IP at times.**

### 1) Careful with WCAG 3 mentions
On the main README, it is okay to say "APCA is the candidate for WCAG 3".

However, this line:

> _Level | Accessibility level as defined by APCA-W3 and WCAG 3: Bronze (minimum), Silver, Gold (higher)._

We can **not** say "Accessibility level as defined by APCA-**W3** and **WCAG 3**". We **_can_** say "Accessibility level as defined by APC-RC". 

Nothing is defined in WCAG 3 at the moment, and therefore **no reference can be made to WCAG 3 or W3C in terms of conformance** until we are at the draft recommendation stage. But that is why IRT and APC-RC... but also, APC-RC is not at a stage of "conformance yet". I might be more comfortable with "Objectives to meet" sort of language, but this is not critical. 

### 2) ARC is changing
I am going to change APCA Readability Criterion to something that does not spell ARC, as an accessibility company already has a product called ARC now. Up in the air as to what, but **APC-RC** will do for the time being.

### 3) Polarity, non-polar, and absolute Lc

This caught my attention:

> _Absolute (**non-polar)** Lc value_ 

I'm sorry Cyril, as you had no way of knowing, but there is a non-polar mode and I'm afraid this is not it.

This can be called "absolute Lc" or something that does not refer to polarity, but not non-polar please, as there are some specific definitions for the non-polar version, and how it will be used.

Because it is woven all through your code, I am more than happy to adjust and issue a pull request for this.

### Related question

It looks to me that throughout the code, the "Lnp" variable is being used often — but I didn't see how polarity was being checked or enforced? It's fine to use the absolute for connecting to a lookup table for instance, but does need to be tokenized in some way to ensure correct BoW/WoB.

While this may seem less important today, there are other color spaces where this will become very important.

Before I do anything, I'll wait to hear from you in terms of how you are handling polarity, particulary for Silver level. 

### 4) x-height marks the spot...

**Regarding font-size:** what is actually important is **xheight**. Does sass have any utilities for using/finding xheight?

### 5) Backwards Scope

Again, here is something that you didn't know about because it is not public facing yet.

There will be one low level that is:
- Non-polar mode only (authorized non polar, not abs(Lc))
- Covers the same text and non-text scope as WCAG 2.2
- Lc 75 = 4.5:1 and Lc 60 = 3:1
- Non-text and very large text may get an Lc 15 break (down to Lc 45) for darker colors (if both darker than #c0c0c0 possibly), TBD.

This is the bassackwards compatible level.

Maybe call it the "Brass" level? Or maybe [**Iron**, LOL ](https://ceruleansphere.com/the-list-of-metal-rules-4dd5739c705f?sk=b92a29f3153d5cffa6458532266834ff)(link to my general article on "metal rules", absolutely nothing at all to do with accessibility).

### Bronze Scope
At the moment, scope for BRONZE is going to be "primary content and elements required to use/nav the site". But not non-polar.

**Note:** the maximum contrast _ONLY_ applies to reverse (negative) Lc values, I.e. -90 or -85. It does not apply to light mode.

**Covered:** placeholders that are labels, nav icons, captions unless only a byline or covered in main content. Data viz needed for understanding (chart lines, pie pieces)

**Not covered:** placeholders that are NOT labels when a form label does exist, disabled controls, copyright, corp logos, ancillary, dataviz not needed for understanding (grid lines, alternating chart row highlighting) and anything not covered by WCAG 2.2.

As always this is interim.

### Silver, Gold

**You're gold man!** amazing job over all, sorry about the errata above, I can help if you like. Seems to me the biggest deal is around the non-polar issue? Renaming to `Lcat` (Lc **a**bsolu**t**e) maybe?? I don't want to muck up any of your logic or workflow... 

For the real non-polar, I don't want to release the _actual_ non-polar mode yet for a variety of reasons. But just FYI, the actual non polar mode does not have a text/bg field, it has hi/lo fields, and the low field is always processed _as if_ it was text, the high field is always bg (even if it is actually being used for text). The hi/lo of course is tested and inverted if needed, so a user can put whatever anywhere, and it acts like the webaim checker.

Nonpolar is only for the backwards compat mode.

Please feel free to hit me up with questions comments etc.

Thank you for reading... and for all your great work!

**Comment by cyrez** [comment]
Hi Andrew! @Myndex 

Thank you very much for this detailed review!

So, step by step:

**About 1:**
- I updated the readme.md with your recommendations
- Same for a11y-apca-sass.scss

**About 2:**
All right! Good to know!

**About 4:**
I don't think there's anything for this in Sass directly.
But in CSS, you can set xheight for any font-family with `font-size-adjust`: https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust
Maybe to mention it in the readme.md as a documentation to properly use the library with pre-adjusted font-size?
It's not the scope of this library, as font-family should be adjusted before to run the a11y-color to have the correct xheight, as not possible directly to know while running the function.

**About 3 and bronze:**
This is a major point and I may have missed the point at first.

It's absolute Lc everywhere.
So you suggested "Lcat". I agree with that, but what does that mean (what does the "at" mean? Absolutely...?)
Or could it be "absLc" as the short variable name?

In this Sass library workflow, using the a11y-color() function (which does pretty much the same thing as your inverted apca, but with a defined color), the polarity is handled before this function manipulates the color using the absolute value of Lc.
In all my tests I got the same results for color pairs as I get on your online APCA Contrast Checker.

For example. you want the color accessible with a specific tint, this will be adjusted in lightness in order to obtain the correct contrast in relation to a background color (and vice versa, because this function can work in two cases, text color to be defined for a defined background color or text color defined for a background color to be defined), a defined use case and level.

So, just need to find a new variable name (`Lcat`or `absLc`) and to remove all "non-polar" mentions and replace with absolute Lc value.

About Bronze and Backwards Scope, it seems to be not clearly defined yet.
Based on your bridge-apca information, i've got an updated code which is then WCAG compliant too (which is not the case right now for all contexts with the current code based on another page found on your site.)

What i think best, is to set clearly that this Bronze level is still in dev version, and not yet beta.
And keep silver and gold as beta (i mean of course for my Sass library).

So, thanks for your comment!

My main question for now, to update my file, is the best naming for the absolute Lc.

**Comment by Myndex** [comment]
Hi @cyrezdev 

Re: font-size-adjust -- yes, familiar, but it only runs in a few placed, is clunkly, and less than ideal.  Just wasn't sure it it was something that could be added/done with SASS.

RE: Variable name: really, anything you like, just not calling it non-polar... I like absLc, it's clear and understandable IMO —— 

My bigger concerns are losing track of positive or negative polarity in a workflow. This is a thing that will be a bigger deal with HDR.

Thank you!!

**Comment by cyrez** [comment]
Hi @Myndex 

Re: font-size-adjust agree about it to be not so useful. About Sass, maybe this could another experiment to be done, but i don't know how you can create a reliable system.
IMO, it is on the frontend designer side to select a correct font, and check it's usuability and xheight to adapt it before using this library or APCA.
Maybe a new paragraph to be added in the readme text to inform users of this library? (even tho i've already mentionned reference fonts, and linked your website pages for controling font size and weight).

Re: variable name: it's done! Updated scss file as well as readme text.

Re: polarity. No issue here in my Sass library as each time i get the absolute Lc value, this is always after the polar Lc value was calculated.

Hope this is better now? :-D

**Comment by cyrez** [comment]
Hi @Myndex,

Just to get some news. Is it ok to make this repo public in beta mode?

Thanks!
Cyril

**Comment by Myndex** [comment]
Oh geezze I’m so sorry Cyril I didn’t realize you were waiting for me…! 
Yes indeed please feel free… the main thing is, as you indicated, needs to be labeled beta because APCA and the RC are beta. WCAG3 should not be mentioned at this time because the AGWG had concerns about some individuals who were making inappropriate claims, so we aren’t promoting WCAG3 right now.

Thank you!!!!

**Comment by cyrez** [comment]
Hi @Myndex,

I'm just following your compliance statement: https://git.apcacontrast.com/documentation/minimum_compliance so that's why i want all to be ok about trademark, mentions and usage. ;-)

I expect to get a few users and feedbacks that could be useful with this Sass library.

As far as APCA will be in beta, this Sass library will be in beta.

Is it still ok to say "APCA™ is the candidate contrast method for WCAG 3"?

Thank you!

Note: and when turn public, do you want to delete this issue? (you said a word about it previsouly...)

**Comment by Myndex** [comment]
Yes whould be fine, and you can probably just close not delete issue, we didn't get into anything proprietary.

Thank you!!

**Comment by cyrez** [comment]
Hi @Myndex !

There we are: i've set the repo to public!

Thank you for your review! Next step: get feedback. ;-)
